name: Auction microservice CI workflow

on:
  push:
    branches: [ "main" ]
    paths:
    - "auction_svc/**"

permissions:
  contents: read

jobs:
  test-lint:

    name: Test & lint using TOX

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python for ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Run tox
      working-directory: auction_svc
      run: |
        tox

  build:

    name: Build & push Docker image
    
    runs-on: ubuntu-latest

    needs: test-lint

    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      working-directory: auction_svc
      run: docker build -t auctions-svc .
    - name: Push the Docker image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker tag auctions-svc ${{ secrets.DOCKER_USERNAME }}/auctions-svc
        docker push ${{ secrets.DOCKER_USERNAME }}/auctions-svc